name: sticker_maker
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.9.0
  get: ^4.6.5
  image_picker: ^1.0.4
  crop_image: ^1.0.11
  stack_board: ^0.1.2
  screenshot: ^2.1.0
  image_gallery_saver: ^2.0.3
  permission_handler: ^11.0.1
  # flutter_staggered_grid_view: ^0.7.0
  # photo_view: ^0.14.0
  # undo: ^1.4.0
  # stick_it: ^1.0.0+2
  emoji_picker_flutter: ^1.6.1
  # animated_emoji: ^2.0.0
  # image_stickers: ^0.0.4
  # lindi_sticker_widget: ^0.1.1
  # flutter_whatsapp_stickers: ^1.0.1+5
  

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0



flutter:



  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  #   - images/a_dot_ham.jpeg



  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  

  
