// import 'package:get/get_navigation/get_navigation.dart';

// int languageIndex = 0;

// class Languages extends Translations {
//   @override
//   Map<String, Map<String, String>> get keys => {
//         /// ==========================> English
//         'en_US': {
//           'Login': 'Login',
//           'Take a Tour': 'Take a Tour',
//           'sri': 'sri',
//           'Register': 'Register',
//           'E-mail': 'E-mail',
//           'Password': 'Password',
//           'Please Enter Email': 'Please Enter Email',
//           'Invalid Email format': 'Invalid Email format',
//           'Please Enter Password': 'Please Enter Password',
//           'Please Enter Valid Password(Min 6 character':
//               'Please Enter Valid Password(Min 6 character',
//           'Forgot Password?': 'Forgot Password?',
//           'Or': 'Or',
//           'Login with Google': 'Login with Google',
//           'Login Successful :)': 'Login Successful :)',
//           'Your Full Name': 'Please Enter full Name',
//           'Please Enter Valid Name': 'Please Enter Valid Name',
//           'Username': 'Username',
//           'Please Enter user Name': 'Please Enter user Name',
//           'Confirm Password': 'Confirm Password',
//           'Password dont Match': 'Password dont Match',
//           'Register with Google': 'Register with Google',
//           'Account created successfully :)': 'Account created successfully :)',
//           //-----------> Home Page
//           'Something went wrong': 'Something went wrong',
//           'Maktba is Empty': 'Maktba is Empty',
//           'Choose Your interest': 'Choose Your interest',
//           'Quran': 'Quran',
//           'Hadith': 'Hadith',
//           'Grammer': 'Grammer',
//           'Nisaab': 'Nisaab',
//           'Popular Books': 'Popular Books',
//           'Maktba ': 'Maktba ',
//           'Asria': 'Asria',
//           'Search Book': 'Search Book',
//           //-----------> Book Detail Page
//           'Book Name | up to 2 lines': 'Book Name | up to 2 lines',
//           'Publisher': 'Publisher',
//           'Class': 'Class',
//           'Category': 'Category',
//           'Volume Number': 'Volume Number',
//           'Published on ': 'Published on ',
//           'Downloads': 'Downloads',
//           'Pages': 'Pages',
//           'Size': 'Size',
//           'About this Book.': 'About this Book.',
//           'Topics of this Book.': 'Topics of this Book.',
//           'Download Now': 'Download Now',
//           'Add New Book': 'Add New Book',
//           'Asri': 'Asri',
//           //-----------> New Book Page
//           'Size: ': 'Size: ',
//           'Book Name': 'Book Name',
//           'Name is required': 'Name is required',
//           'Field:': 'Field:',
//           'Class:': 'Class:',
//           'Volume No.': 'Volume No.',
//           'Book Topics': 'Book Topics',
//           'Book Details': 'Book Details',
//           'Upload Book': 'Upload Book',
//           'Error Uploading Book': 'Error Uploading Book',
//           'Your PDF Content': 'Your PDF Content',
//           '': '',
//         },

//         /// ==========================> Urdu
//         'ur_PK': {
//           'Login': 'لاگ ان کریں',
//           'Take a Tour': ' مکتبہ کا دورہ کریں',
//           'sri': 'sri',
//           'Register': 'رجسٹریشن',
//           'E-mail': 'ای میل',
//           'Password': 'پاسورڈ',
//           'Please Enter Email': 'براہ مہربانی ای میل درج کریں',
//           'Invalid Email format': 'غیر قانونی ای میل فارمیٹ',
//           'Please Enter Password': 'براہ مہربانی پاسورڈ درج کریں',
//           'Please Enter Valid Password(Min 6 character':
//               'برائے مہربانی درست پاس ورڈ درج کریں (منٹ 6 حروف)',
//           'Forgot Password?': 'پاسورڈ بھول گئے؟',
//           'Or': 'یا',
//           'Login with Google': 'گوگل کے ساتھ لاگ ان کریں',
//           'Login Successful :)': ': لوگن ہو گیا )',
//           'Your Full Name': 'آپ کا پورا نام',
//           'Please Enter full Name': 'براہ مہربانی مکمل نام درج کریں',
//           'Please Enter Valid Name': 'براہ کرم درست نام درج کریں',
//           'Username': 'صارف نام',
//           'Please Enter user Name': 'برائے مہربانی صارف نام درج کریں',
//           'Confirm Password': 'پاس ورڈ کی تصدیق کریں',
//           'Password dont Match': 'پاس ورڈ میل نہیں کھاتا',
//           'Register with Google': 'گوگل کے ساتھ رجسٹر کریں',
//           'Account created successfully :)':
//               ' (:اکاؤنٹ کامیابی کے ساتھ بنایا گیا',
//           //-----------> Home Page
//           'Something went wrong': 'کچھ غلط ہو گیا',
//           'Maktba is Empty': 'مکتبہ خالی ہے',
//           'Choose Your interest': 'اپنی دلچسپی کا انتخاب کریں',
//           'Quran': 'قرآن',
//           'Hadith': 'حدیث',
//           'Grammer': 'گرائمر',
//           'Nisaab': 'نصاب',
//           'Popular Books': 'مشہور کتابیں',
//           'Maktba ': 'مکتبہ ',
//           'Asria': 'اثریہ',
//           'Search Book': 'کتاب کی تلاش',
//           //-----------> Book Detail Page
//           'Book Name | up to 2 lines': 'کتاب کا نام | 2 لائنوں تک',
//           'Publisher': 'ناشر',
//           'Class': 'کلاس',
//           'Category': 'زمرہ',
//           'Volume Number': 'جلد نمبر',
//           'Published on ': 'شائع کی تاریخ',
//           'Downloads': 'ڈاؤن لوڈ',
//           'Pages': 'صفحات',
//           'Size': 'سائز',
//           'About this Book.': 'کتاب کی تفصیل',
//           'Topics of this Book.': 'اس کتاب کے موضوعات',
//           'Download Now': 'ابھی ڈاؤن لوڈ کریں',
//           'Add New Book': 'نئی کتاب شامل کریں',
//           'Asri': 'اثری',
//           //-----------> New Book Page
//           'Size: ': 'سائز : ',
//           'Book Name': 'کتاب کا نام',
//           'Name is required': 'نام کی ضروری ہے',
//           'Field:': 'فیلڈ:',
//           'Class:': 'کلاس:',
//           'Volume No.': 'جلد نمبر:',
//           'Book Topics': 'کتاب کے موضوعات',
//           'Book Details': 'کتاب کی تفصیل',
//           'Upload Book': 'کتاب اپ لوڈ کریں',
//           'Error Uploading Book': 'کتاب اپلوڈ کرنے میں مسئلہ',
//           'Your PDF Content': 'اہجئ ہئ ڈی ایف کا مواد',
//           '': '',
//         }
//       };
// }
